# -*- mode: ruby -*-
# vi: set ft=ruby :

# Add Ruby Script
$script = <<EOS
  rm /etc/systemd/network/*
  cat > "/etc/systemd/network/10-static-en.network"<<EOF
[Match]
Name=eth0
[Network]
Address=192.168.0.10/24
Gateway=192.168.0.1
DNS=192.168.62.2
EOF
systemctl restart systemd-networkd
EOS

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.


  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "photon-tester"
  config.ssh.username="vagrant"
  config.vm.guest=:redhat
#  config.ssh.private_key_path=File.expand_path("/Users/shawnho/.ssh/id_rsa", __FILE__) 
  config.vm.provider "vmware_fusion" do |v|
    v.gui=true
    v.vm.hostname="photon-1"
    v.vmx['ethernet0.virtualDev']="vmxnet3"
    config.vm.provision "shell" do |s|
      s.path = "configAddress.sh"
      s.args = "192.168.62.20"   
    end
  end
end
